server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Rutas de cada microservicio
spring.cloud.gateway.routes[0].id=ms-usuarios
spring.cloud.gateway.routes[0].uri=lb://ms-usuarios
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[1].id=ms-sucursales
spring.cloud.gateway.routes[1].uri=lb://ms-sucursales
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/sucursales/**

spring.cloud.gateway.routes[2].id=ms-categorias-menu
spring.cloud.gateway.routes[2].uri=lb://ms-categorias-menu
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/categorias/**

spring.cloud.gateway.routes[3].id=ms-menu
spring.cloud.gateway.routes[3].uri=lb://ms-menu
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/menu/**

spring.cloud.gateway.routes[4].id=ms-pedidos
spring.cloud.gateway.routes[4].uri=lb://ms-pedidos
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.routes[5].id=ms-pagos
spring.cloud.gateway.routes[5].uri=lb://ms-pagos
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.routes[6].id=ms-inventario
spring.cloud.gateway.routes[6].uri=lb://ms-inventario
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/inventario/**

spring.cloud.gateway.routes[7].id=ms-proveedores
spring.cloud.gateway.routes[7].uri=lb://ms-proveedores
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/proveedores/**

spring.cloud.gateway.routes[8].id=ms-empleados
spring.cloud.gateway.routes[8].uri=lb://ms-empleados
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/empleados/**

spring.cloud.gateway.routes[9].id=ms-reservas
spring.cloud.gateway.routes[9].uri=lb://ms-reservas
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/reservas/**