server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

# Rutas de cada microservicio
#MS-USUARIOS (puerto 8082)
spring.cloud.gateway.server.webflux.routes[0].id=ms-usuarios
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-usuarios
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.server.webflux.routes[1].id=ms-roles
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-usuarios
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/roles/**

#MS-SUCURSALES (puerto 8083)
spring.cloud.gateway.server.webflux.routes[2].id=ms-sucursales
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-sucursales
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/sedes/**

#MS-CATEGORIAS-MENU (puerto 8087)
spring.cloud.gateway.server.webflux.routes[3].id=ms-categorias-menu
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-categorias-menu
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/categorias/**

spring.cloud.gateway.server.webflux.routes[4].id=ms-etiquetas-nutricionales
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ms-categorias-menu
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/etiquetas/**

#MS-MENU (puerto 8084)
spring.cloud.gateway.server.webflux.routes[5].id=ms-platos
spring.cloud.gateway.server.webflux.routes[5].uri=lb://ms-menu
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/platos/**

spring.cloud.gateway.server.webflux.routes[6].id=ms-tipos-plato
spring.cloud.gateway.server.webflux.routes[6].uri=lb://ms-menu
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/tipos-plato/**

spring.cloud.gateway.server.webflux.routes[7].id=ms-programacion
spring.cloud.gateway.server.webflux.routes[7].uri=lb://ms-menu
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/programacion/**

#MS-PEDIDOS (puerto 8085)
spring.cloud.gateway.server.webflux.routes[8].id=ms-pedidos
spring.cloud.gateway.server.webflux.routes[8].uri=lb://ms-pedidos
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/pedidos/**

#MS-PAGOS (puerto 8086)
spring.cloud.gateway.server.webflux.routes[9].id=ms-pagos
spring.cloud.gateway.server.webflux.routes[9].uri=lb://ms-pagos
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/pagos/**

#MS-INVENTARIO (puerto 8091)
spring.cloud.gateway.server.webflux.routes[10].id=ms-ingredientes
spring.cloud.gateway.server.webflux.routes[10].uri=lb://ms-inventario
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/ingredientes/**

spring.cloud.gateway.server.webflux.routes[11].id=ms-movimientos-stock
spring.cloud.gateway.server.webflux.routes[11].uri=lb://ms-inventario
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/movimientos/**

spring.cloud.gateway.server.webflux.routes[12].id=ms-tipos-movimiento
spring.cloud.gateway.server.webflux.routes[12].uri=lb://ms-inventario
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/tipos-movimiento/**

#MS-PROVEEDORES (puerto 8088)
spring.cloud.gateway.server.webflux.routes[13].id=ms-proveedores
spring.cloud.gateway.server.webflux.routes[13].uri=lb://ms-proveedores
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/api/proveedores/**

spring.cloud.gateway.server.webflux.routes[14].id=ms-ordenes-compra
spring.cloud.gateway.server.webflux.routes[14].uri=lb://ms-proveedores
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/api/ordenes/**

#MS-EMPLEADOS (puerto 8090)
spring.cloud.gateway.server.webflux.routes[15].id=ms-empleados
spring.cloud.gateway.server.webflux.routes[15].uri=lb://ms-empleados
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/api/empleados/**

spring.cloud.gateway.server.webflux.routes[16].id=ms-turnos-empleado
spring.cloud.gateway.server.webflux.routes[16].uri=lb://ms-empleados
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/api/turnos-empleado/**

#MS-RESERVAS (puerto 8089)
spring.cloud.gateway.server.webflux.routes[17].id=ms-reservas
spring.cloud.gateway.server.webflux.routes[17].uri=lb://ms-reservas
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/api/reservas/**

spring.cloud.gateway.server.webflux.routes[18].id=ms-turnos-disponibles
spring.cloud.gateway.server.webflux.routes[18].uri=lb://ms-reservas
spring.cloud.gateway.server.webflux.routes[18].predicates[0]=Path=/api/turnos/**